name: 'TerraformOnAzure Challenge 3 Web App CI/CD'

on: [push]
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID  }}
  DB_PWD: ${{ secrets.DB_PWD }}
  REPOURL: 'https://github.com/OmegaMadLab/AzureEats-Website'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    outputs:
      rgname:     ${{ steps.tfapply.outputs.rgname }}
      webappname: ${{ steps.tfapply.outputs.webappname }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.27

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var 'dbpassword=${{ secrets.DB_PWD }}'
    
    - name: Terraform Apply
      id: tfapply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
            terraform apply -var 'dbpassword=${{ secrets.DB_PWD }}' -auto-approve
            terraform output rgname
            terraform output webappname
            RGNAME=$(terraform output rgname -no-color)
            WEBAPPNAME=$(terraform output webappname -no-color)
            echo $RGNAME
            echo $WEBAPPNAME 
            echo ::set-output name=rgname::$RGNAME
            echo ::set-output name=webappname::$WEBAPPNAME
  
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: terraform
    
    steps:
    #- name: Login to AZ CLI
    #  uses: azure/login@v1.1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    #- name: AzCli configure CI
    #  run: az webapp deployment source config --branch master --name ${{needs.terraform.outputs.webappname}} --repo-url $REPOURL --resource-group ${{needs.terraform.outputs.rgname}}

    - name: test out
      run: |
            echo ${{needs.terraform.outputs.webappname}}
            echo ${{needs.terraform.outputs.rgname}}
            echo $REPOURL
