name: 'TerraformOnAzure Challenge 3 Web App CI/CD'

on: [push]
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID  }}
  DB_PWD: ${{ secrets.DB_PWD }}
  REPOURL: 'https://github.com/OmegaMadLab/AzureEats-Website'

jobs:
  terraform:
    name: 'Terraform-CICD'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to AZ CLI
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.27

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var 'dbpassword=${{ secrets.DB_PWD }}'
    
    - name: Terraform Apply
      id: tfapply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -var 'dbpassword=${{ secrets.DB_PWD }}' -auto-approve
           
    - name: Get output rgname
      id: get-rgname
      run: terraform output -no-color rgname

    - name: Get output webappname
      id: get-webappname
      run: terraform output -no-color webappname
        
    - name: AzCli configure CI
      run: |
              az account list
              RGNAME=${{ steps.get-rgname.outputs.stdout }}
              WEBAPPNAME=${{ steps.get-webappname.outputs.stdout }}
              az webapp deployment source config --branch master --name $WEBAPPNAME --repo-url $REPOURL --resource-group $RGNAME
