name: 'TerraformOnAzure Challenge 3 Web App CI/CD'

on: [push]
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID  }}
  DB_PWD: ${{ secrets.DB_PWD }}
  REPOURL: 'https://github.com/OmegaMadLab/AzureEats-Website'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to AZ CLI
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var 'dbpassword=${{ secrets.DB_PWD }}'
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
            terraform apply -var 'dbpassword=${{ secrets.DB_PWD }}' -auto-approve
            $RGNAME=terraform output rgname
            echo "::set-env name=RGNAME::$RGNAME"
            $WEBAPPNAME=terraform output webappname
            echo "::set-env name=WEBAPPNAME::$WEBAPPNAME"
            
    - name: AzCli configure CI
      run: az webapp deployment source config --branch master --name $WEBAPPNAME --repo-url $REPOURL --resource-group $RGNAME
    

